config/routes.rb
Buybuysell::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
  end

  resources :listings, only: [:index, :new, :show, :create, :destroy] do
    member do
      get :followers
    end
    resources :comments
    resources :bids, :defaults => { :biddable => 'listing' }
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :listing_relationships, only: [:create, :destroy]
  get 'tags/:tag', to: 'listings#index', as: :tag

  root to: 'static_pages#home'

  devise_scope :user do
    get "signup", to: 'devise/registrations#new'
    get "signin", to: "devise/sessions#new"
    delete "signout", to: 'devise/sessions#destroy'
  end

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :title, :description, :image, :tag_list, :price, :followers
  belongs_to :user

  # has_many :listing_relationships, foreign_key: "followed_id", dependent: :destroy
  # has_many :followed_users, through: :listing_relationships, source: :followed

  has_many :reverse_listing_relationships, foreign_key: "followed_id",
                                   class_name:  "ListingRelationship",
                                 dependent:   :destroy
  has_many :followers, through: :reverse_listing_relationships, source: :follower

  has_many :bids, as: :biddable

  mount_uploader :image, ImageUploader
  acts_as_taggable
  acts_as_commentable
  is_impressionable

  validates :title, presence: true, length: { maximum: 70 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :user_id, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  default_scope order: 'listings.created_at DESC'

  include PgSearch
  pg_search_scope :search, against: [:title],
    using: {tsearch: {dictionary: "english"}},
    associated_against: {tags: [:name]}

  def self.text_search(query)
    if query.present?
      search(query)
    else
      scoped
    end
  end

  # Returns listings from the users being followed by the given user.
  # SELECT * FROM listings WHERE user_id IN (SELECT followed_id FROM listing_relationships WHERE follower_id = 1) R user_id = 1
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM listing_relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :update, :create, :destroy, :followers]
  before_filter :correct_user, only: [:edit, :update, :destroy, :followers]
  impressionist actions: [:show]

  def show
    @listing = Listing.find(params[:id])
    @comments = @listing.comments.paginate(page: params[:page])
    @bids = @listing.bids
    if signed_in?
      @bid = Bid.new
    end
    @comment = Comment.new
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.build(params[:listing])
    if @listing.save
      flash[:success] = "Your listing has been successfully created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    #@listings = Listing.all
    if params[:tag]
      @listings = Listing.tagged_with(params[:tag]).paginate(page: params[:page])
    else
      @listings = Listing.text_search(params[:query]).paginate(page: params[:page])
    end
  end

  def edit

  end

  def update

  end

  def destroy
    @listing.destroy
    redirect_to root_url
  end

  def followers
    @title = "Followers"
    @listing = Listing.find(params[:id])
    @followers = @listing.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  # def add_new_comment
  #   @listing = Listing.find(params[:id])
  #   @listing.comments << Listing.new(params[:comment])
  #   redirect_to :action => :show, :id => @listing
  # end

  # def comments
  #   @title = "Comments"
  #   @listing = Listing.find(params[:id])
  #   @comments = @listing.comments.paginate(page: params[:page])
  #   render 'show_comment'
  # end

  private
  def correct_user
    @listing = current_user.listings.find_by_id(params[:id])
    redirect_to root_url if @listing.nil?
  end
end

app/views/listings/_fields.html.erb
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :price %>
<%= f.text_field :price %>

<%= f.label :image, "Upload Images" %>
<%= f.file_field :image, placeholder: "Upload photos" %>

<%= f.label :description %>
<%= f.text_area :description, placeholder: "Product Description" %>

<%= f.label :tag_list %>
<%= f.text_field :tag_list, placeholder: "Tags (separated by commas)" %>

app/views/listings/_form.html.erb
<%= simple_form_for @listing do |f| %>

<%= f.input :title, placeholder: "Title for your listing" %>

<%= f.input :price %>

<%= f.label :image %>
<%= f.file_field :image, placeholder: "Upload photos" %>

<%= f.input :description, placeholder: "Product Description" %>

<%= f.input :tag_list, placeholder: "Tags (separated by commas)"  %>

<div class="btn-group-wrap">
  <%= f.button :submit, "Start Selling", class: "button" %>
  <%= submit_tag 'Cancel', type: :reset, class: 'btn btn-large btn-danger' %>
</div>
<% end %>

app/views/listings/_listing.html.erb
<div class="listing-block">
  <div class="listing-image-block">
    <span class="image_placeholder">
      <%= image_tag listing.image_url(:thumb).to_s %>
    </span>
  </div>
  <div class="listing-content-block">
    <span class="listing-title">
      <%= link_to "#{listing.title} - $#{listing.price}", listing %>
    </span>
    <p><%= listing.description %></p>
  </div>
  <ul style="list-style:none;margin: 0;">
    <div class="listing-button-block">
      <li style="padding:0px;">
        <div class="listing-star-button <%= "starred" if signed_in? and listing.user == current_user or current_user.following?(listing)%>">
          <%= link_to "#{listing.followers.count + 1}", followers_listing_path(listing), class: "listing-star-link" %>
        </div>
      </li>
      <li style="padding:0px;">
        <div class="listing-readmore-button">
          <%= link_to "read more", listing, class: "listing-readmore-link" %>
        </div>
      </li>
    </div>
  </ul>
</div>

app/views/listings/_star.html.erb
<%= form_for(current_user.listing_relationships.build(followed_id: @listing.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Star", class: "button" %>
<% end %>

app/views/listings/_star_form.html.erb
<% unless current_user?(@listing.user) %>
  <div id="star_form">
  <% if current_user.following?(@listing) %>
    <%= render 'unstar' %>
  <% else %>
    <%= render 'star' %>
  <% end %>
  </div>
<% end %>

app/views/listings/_unstar.html.erb
<%= form_for(current_user.listing_relationships.find_by_followed_id(@listing.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unstar", class: "btn btn-large" %>
<% end %>

app/views/listings/index.html.erb
<% if params[:query].blank? %>
<% provide(:title, 'All listings') %>
<h1>All Listings</h1>
<% else %>
<% provide(:title, params[:query]) %>
<h1>Results for <i><%= params[:query] %></i>...</h1>
<% end %>

<center>
  <div class="listings">
    <%= render @listings %>
  </div>
</center>


<%= will_paginate %>

app/views/listings/new.html.erb
<% provide(:title, 'Create New Listing') %>

<h1>Create New Listing</h1>
<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

app/views/listings/show.html.erb
<!-- Runs when /listings/1/ is accessed -->
<% provide(:title, @listing.title) %>
<% right_user = current_user?(@listing.user) %>

<div class="row">
  <aside class="span9">
    <h2><%= @listing.title %> - $<%= @listing.price %></h2>
    <ul class="listings">
      <%= render @listing %>
    </ul>
    <% if not right_user and signed_in? %>
    <section>
      <%= render 'star_form' %>
      <%= button_to "Message #{@listing.user.user_name}", new_conversation_path(email: @listing.user.email), method: "get", class: "button" %>
      <% if right_user %>
      <%= link_to "delete", @listing, method: :delete,
      data: { confirm: "Delete your listing?" },
      title: @listing.title %>
      <% end %>
    </section>
    <section>
      <p>Unique Page Views: <%= @listing.impressionist_count(filter: :ip_address) %></p>
    <span>Tags: <%= raw @listing.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(@listing.created_at) %> ago.
    </span>
      </section>
      <% end %>
    </aside>
    <% if right_user %>
    <div class="span3">
      <h3>Followers (<%= @listing.followers.count + 1 %>)</h3>
      <%= render @listing.user %>
      <%= render @listing.followers %>
    </div>
    <% end %>
    <% if signed_in? %>
    <div class="span3">
      <h3>Bids</h3>
      <%= render @bids %>
      <% if not right_user %>
      <%= simple_form_for [@listing, @bid] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.input :amount %>
      <div class="btn-group-wrap">
        <%= f.submit "Place New Bid", class: "button" %>
      </div>
      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
  <hr />
  <h2>Comments</h2>
  <%= render @comments %>
  <%= will_paginate(@comments) %>


  <%= simple_form_for [@listing, @comment] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.input :comment %>
  <div class="btn-group-wrap">
    <%= f.submit "Post Comment", class: "button" %>
    <%= submit_tag 'Cancel', type: :reset, class: 'btn btn-large btn-danger' %>
  </div>
  <% end %>

app/views/listings/show_follow.html.erb
<!-- Runs when /listings/1/followers is accessed -->

<% provide(:title, @title) %>
<h3>Followers (<%= @listing.followers.count + 1 %>)</h3>
<%= render @listing.user %>
<%= render @followers %>