config/routes.rb
Buybuysell::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
  end

  resources :listings, only: [:index, :new, :show, :create, :destroy] do
    member do
      get :followers
    end
    resources :comments
    resources :bids, :defaults => { :biddable => 'listing' }
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :listing_relationships, only: [:create, :destroy]
  get 'tags/:tag', to: 'listings#index', as: :tag

  root to: 'static_pages#home'

  devise_scope :user do
    get "signup", to: 'devise/registrations#new'
    get "signin", to: "devise/sessions#new"
    delete "signout", to: 'devise/sessions#destroy'
  end

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul class="nav pull-right">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid hidden-phone" style="padding-left: 190px; padding-right: 65px; width: auto; position: relative;">
      <div class="header-left">
        <ul class="nav" style="margin: 0px;">
          <li>
            <%= link_to "buybuysell", root_path, id: "logo" %>
          </li>
        </ul>
      </div>
      <ul class="nav" style="width: 100%;">
        <li>
          <%= form_tag listings_path, method: :get, class: "navbar-search" do %>
          <%= text_field_tag :query, params[:query], class: "search-query", placeholder: "Search for anything.." %>
          <% end %>
        </li>
      </ul>
      <div class="header-right">
        <ul class="nav pull-right">
          <li id="fat-menu" class="dropdown">
            <a href="#" title="Power" class="dropdown-toggle" data-toggle="dropdown" style="padding: 17px 20px 12px 20px;">
              <%= image_tag 'header/power.svg', class: "svg power-image" %>
            </a>
            <ul class="dropdown-menu">
              <% if signed_in? %>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete", style: "text-align:center;" %>
              </li>
              <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
              <li><%= link_to "Twitter", user_omniauth_authorize_path(:twitter) %></li>
              <li><%= link_to "Facebook", user_omniauth_authorize_path(:facebook) %></li>
              <li><%= link_to "Google", user_omniauth_authorize_path(:google_oauth2) %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <div class="container-fluid visible-phone" style="padding-right: 65px; width: auto; position: relative;">
      <ul class="nav" style="width: 100%;">
        <li>
          <%= form_tag listings_path, method: :get, class: "navbar-search", style: "margin-left: 5px;" do %>
          <%= text_field_tag :query, params[:query], class: "search-query", placeholder: "Search for anything.." %>
          <% end %>
        </li>
      </ul>
      <div class="header-right">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="container-fluid nav-collapse">
          <ul class="nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<!-- //Sidebar Options
.bs-docs-sidenav {
    background-color: @navbarBackground;
    border: 1px solid rgba(0, 0, 0, 0.15);
    .rounded-corners(4px);
    li {
        max-width: 50px;
        a {
          padding: 9px;
        }
        a:hover {
            background-color: @liHighlightColor;
            .box-shadow(inset #7c1d08 0px 0px 1px);
        }
    }
} -->

<ul class="nav nav-list bs-docs-sidenav affix">
  <li>
    <a rel="tooltip" href="<%= root_path %>" title="Starred Listings" data-placement="right">
      <%= image_tag 'sidebar/starred.svg', size: "30x30" %>
    </a>
  </li>
  <li>
    <a data-placement="right" rel="tooltip" href="<%= conversations_path %>" title="Messages">
      <%= image_tag 'sidebar/messages.svg', size: "30x30" %>
    </a>
  </li>
  <li>
    <a data-placement="right" rel="tooltip" href="<%= listings_path %>" title="Tags">
      <%= image_tag 'sidebar/categories_tag.svg', size: "30x30" %>
    </a>
  </li>
  <li>
    <a data-placement="right" rel="tooltip" href="<%= user_path(current_user) %>" title="My Profile">
      <%= image_tag 'sidebar/profile.svg', size: "30x30" %>
    </a>
  </li>
  <li>
    <a data-placement="right" rel="tooltip" href="<%= new_listing_path %>" title="Create Listing">
      <%= image_tag 'sidebar/addlisting.svg', size: "30x30" %>
    </a>
  </li>
</ul>

app/views/layouts/_twitter_fluid.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Buybuysell" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Buybuysell</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/_utilitybar.html.erb
<div class="navbar navbar-fixed-bottom visible-phone">
  <div class="navbar-inner">
    <div class="container-fluid" style="width:100%;">
      <ul class="nav" style="margin: 0px; width: 100%;">
        <li>
          <div class="utilitybar-icons utilitybar-spacing">
            <%= link_to image_tag("utilitybar/link-mailbox.svg", class: "svg"), conversations_path, class: "utilitybar-link" %>
          </div>
        </li>
        <li>
          <div class="utilitybar-icons utilitybar-spacing" style="margin-left: 25%;">
            <%= link_to image_tag("utilitybar/link-profile.svg", class: "svg"), user_path(current_user), class: "utilitybar-link" %>
          </div>
        </li>
        <li>
          <div class="utilitybar-icons utilitybar-spacing" style="margin-left: 50%;">
            <%= link_to image_tag("utilitybar/link-browse.svg", class: "svg"), listings_path, class: "utilitybar-link" %>
          </div>
        </li>
        <li>
          <div class="utilitybar-icons utilitybar-spacing" style="margin-left: 75%;">
            <%= link_to image_tag("utilitybar/link-listing.svg", class: "svg"), new_listing_path, class: "utilitybar-link" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta content='width=device-width, initial-scale=1.0' name='viewport'>
  <%= render 'layouts/shim' %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'favicons/144x144favicon.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'favicons/114x114favicon.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'favicons/72x72favicon.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'favicons/57x57favicon.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicons/32x32favicon.png', :rel => 'shortcut icon' %>
</head>
<body style='font-family: "Quicksand", Arial, sans-serif;'>

  <%= render 'layouts/header' %>
  <div class="container" style="padding-top: 15px;">

    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>

    <% if Rails.env.development? %>
    <%= debug(params) %>
    <div class="responsive-dump">
      <h4>Visible on...</h4>
      <p>Green checkmarks indicate that class is visible in your current viewport.</p>
      <ul class="responsive-utilities-test">
        <li>Phone<span class="visible-phone">&#10004; Phone</span></li>
        <li>Tablet<span class="visible-tablet">&#10004; Tablet</span></li>
        <li>Desktop<span class="visible-desktop">&#10004; Desktop</span></li>
      </ul>
      <h4>Hidden on...</h4>
      <p>Here, green checkmarks indicate that class is hidden in your current viewport.</p>
      <ul class="responsive-utilities-test hidden-on">
        <li>Phone<span class="hidden-phone">&#10004; Phone</span></li>
        <li>Tablet<span class="hidden-tablet">&#10004; Tablet</span></li>
        <li>Desktop<span class="hidden-desktop">&#10004; Desktop</span></li>
      </ul>
    </div>
    <% end %>

  </div>

  <% if signed_in? %>
  <%= render 'layouts/utilitybar' %>
  <% end %>

  <%= javascript_include_tag "application" %>
</body>
</html>